# Site settings
title: ml-perspectives blog
email: rahul@cse.iitm.ac.in
description: > # Use this format to handle multiline text
  Blog to discuss various topics in machine learning theory
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ml-perspectives.github.io" # Ensure proper spacing and quotes
twitter_username: VashishtRahul37
github_username: ml-perspectives

# Build settings
theme: just-the-docs
just_the_docs:
  collapse_section_nav: true
  auxiliary_classes_path: "_sass/custom"
  logo: "assets/images/logo.png" # Ensure proper spacing
  search_enabled: true
  search:
    hint_text: "Search..."
    min_search_length: 2
    layout: horizontal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
